### ISSUE TITLE
Add log_connection_execute?

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequel-impala#17]
As part of outcomesinsights/sequelizer#7, @jeremyevans recommended I call #log_connection_execute to issue my SET commands.  However, the sequel-impala adapter doesn't seem to implement this method anywhere.  

Instead, I'm calling Impala::Connection#execute but that requires Sequelizer to detect and close the cursor that is returned.

I'm not sure where/how to implement #log_connection_execute, but I think this needs to be done.

**Comment by jeremyevans** [comment]
log_connection_execute is a Database method (https://github.com/jeremyevans/sequel/blob/9cdb740c48b8fdb7407ca1961377d86ddbf523ae/lib/sequel/database/logging.rb#L68):

```ruby
    def log_connection_execute(conn, sql)
      log_connection_yield(sql, conn){conn.public_send(connection_execute_method, sql)}
    end
```

The impala and rbhive adapters already define Database#connection_execute_method, so the default definition should work.  I don't think sequel-impala needs changes for this.
