### ISSUE TITLE
Capture profiles, query_ids for DDL statements?

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequel-impala#28]
The methods #query_id and #profile are defined on Dataset, not Database, so I can't call something like:

db.query_id(:fetch_name).profile(:fetch_name).create_table!(:table_name, as: db[:some_other_table])

I need to be able to diagnose and get profiles for these kinds of DDL statements.

If at all possible, can you please enable these methods for Database?

**Comment by aguynamedryan** [comment]
@jeremyevans, I've made a terrible hack to make this work for me for the moment, but if you can clean it up and make it nicer, I'd really appreciate it.  Thanks!

**Comment by jeremyevans** [comment]
I don't think a method chaining approach will work here.  I think the only workable API will be block based, and you'll get the query_id/profile for the last id executed.  I'll work on that shortly.

If you want to expand it later, you could probably an array of query_ids/profiles, and it will record them in order.
