### ISSUE TITLE
Invalidate Metadata after Dropping a Table

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequel-impala#30]
We're running into an issue where even though a table gets dropped in Impala, some part of the system is "remembering" the table's old schema so that when we create the table after dropping it, we can't query the table because the new table's data conflicts with the old table's schema.  The way to fix this issue is to ask Impala to refresh it's cache regarding the table's schema.  The command to do that is [INVALIDATE METADATA](https://www.cloudera.com/documentation/enterprise/5-13-x/topics/impala_invalidate_metadata.html#invalidate_metadata)

I'd like it so that we could pass a new option to drop_table/drop_table!/drop_table?

- invalidate_metadata:
  - truthy/:table => executes the following SQL after dropping the table "invalidate metadata `db_name`.`table_name`"
  - :database => executes the following SQL after dropping the table "invalidate metadata `db_name`"
  - :all => executes the following SQL after dropping the table "invalidate metadata"

**Comment by jeremyevans** [comment]
After reading the impala documentation, I don't think the `:database` value would make sense.  `INVALIDATE METADATA foo` assumes foo is a table in the current database. There does not appear to be a way to invalidate the metadata all tables in the given database, other than attempting to retrieve all tables in the database and calling `INVALIDATE METADATA db.table` for each.
